=== Rinku1806/Java_Sel_Projects/DataDrivenFramework_Javab_XmlData_TestNgRunner/target/test-classes/xmlData/Jpetdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Jpet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="DashBoardTest">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="verifyAvailablePets">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                    <xs:element name="username" type="xs:string" />
                    <xs:element name="password" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="verifyAllPets">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                    <xs:element name="username" type="xs:string" />
                    <xs:element name="password" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="HomePageTest">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="VerifyHomePageTitle">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="StoreEntryTest">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="VerifySignInButtonPresence">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                    <xs:element name="username" type="xs:string" />
                    <xs:element name="password" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="VerifyStoreEntryTitle">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                    <xs:element name="username" type="xs:string" />
                    <xs:element name="password" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Verifylogin">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="browserName" type="xs:string" />
                    <xs:element name="runmode" type="xs:string" />
                    <xs:element name="username" type="xs:string" />
                    <xs:element name="password" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Rinku1806/Java_Sel_Projects/DataDrivenFramework_Javab_XmlData_TestNgRunner/src/test/resources/xmlData/Jpetdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jpet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Jpetdata.xsd">
<DashBoardTest>
<verifyAvailablePets><browserName>chrome</browserName><runmode>Y</runmode><username>j2ee</username><password>j2ee</password></verifyAvailablePets>
<verifyAllPets><browserName>chrome</browserName><runmode>Y</runmode><username>j2ee</username><password>j2ee</password></verifyAllPets>
</DashBoardTest>
<HomePageTest>
<VerifyHomePageTitle><browserName>chrome</browserName><runmode>Y</runmode></VerifyHomePageTitle>
</HomePageTest>
<StoreEntryTest>
<VerifySignInButtonPresence><browserName>chrome</browserName><runmode>Y</runmode><username>j2ee</username><password>j2ee</password></VerifySignInButtonPresence>
<VerifyStoreEntryTitle><browserName>chrome</browserName><runmode>Y</runmode><username>j2ee</username><password>j2ee</password></VerifyStoreEntryTitle>
<Verifylogin><browserName>chrome</browserName><runmode>Y</runmode><username>j2ee</username><password>j2ee</password></Verifylogin></StoreEntryTest>
</Jpet>
